completing the ReverseInteger7 task
CHAriina/ScnSoft-Education pull request #7
Opened 2024-04-01 04:05 UTC by CHAriina

2024-04-01 05:20 UTC, dsubotkovsky commented on ScnSoft-Education/LeetCodeTraining.Tests/ReverseInteger.Tests.cs
> +        [InlineData(1534236469, 0)] // Пример переполнения
use English language

2024-04-01 05:20 UTC, dsubotkovsky commented on ScnSoft-Education/LeetCodeTraining/ReverseInteger7/ReverseInteger.cs
> +            int digit = inputNumber % 10;
'digit' and 'inputNumber' are using in 18 line. Move this code in that place

2024-04-02 10:18 UTC, CHAriina commented on ScnSoft-Education/LeetCodeTraining.Tests/ReverseInteger.Tests.cs
> +        [InlineData(1534236469, 0)] // Пример переполнения
The Russian language has been replaced

2024-04-02 10:19 UTC, CHAriina commented on ScnSoft-Education/LeetCodeTraining/ReverseInteger7/ReverseInteger.cs
> +            int digit = inputNumber % 10;
the location of the code lines has been changed

2024-04-02 10:51 UTC, dsubotkovsky requested changes

2024-04-02 10:51 UTC, dsubotkovsky commented on ScnSoft-Education/LeetCodeTraining/Properties/launchSettings.json
> +      "workingDirectory": "C:\\Users\\Arisha\\Desktop\\EDUCATION\\ScnSoft-Education\\LeetCodeTraining\\TwoSum1"
remove this profile file

2024-04-03 05:41 UTC, CHAriina commented on ScnSoft-Education/LeetCodeTraining/Properties/launchSettings.json
> +      "workingDirectory": "C:\\Users\\Arisha\\Desktop\\EDUCATION\\ScnSoft-Education\\LeetCodeTraining\\TwoSum1"
removed

2024-04-03 06:07 UTC, merged